name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.0
      options: --volume /root/.m2:/root/.m2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: mvn clean install

