name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn -B -DskipTests clean package

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn test
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/*.xml
          
  find-path: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: print working Directory
      - run: pwd
     
  deliver:
    runs-on: ubuntu-latest
    needs: test
      steps:
      - uses: actions/checkout@v2
      - run: ls -la ./jenkins/scripts/  # List files to verify the script exists
      - run: chmod +x ./jenkins/scripts/deliver.sh
      - run: ./jenkins/scripts/deliver.sh
