name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
    - run: mvn -B -DskipTests clean package

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
    - run: mvn test
    - uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/*.xml

  deliver:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - run: ./jenkins/scripts/deliver.sh

